### ISSUE TITLE
Error Encountered

### ISSUE THREAD

**Issue by deepanshuparuthi** [Karan-Malik/FaceMaskDetector#12]
please help me resolve this
![error](https://user-images.githubusercontent.com/83217147/117420606-6194b900-af3b-11eb-8fb3-fcf6ef78aa35.png)

**Comment by Karan-Malik** [comment]
The error you are experiencing is occurring due to the deprecation of the predict_classes() function in Keras. The code has been updated in the repo and the error has been resolved. You can clone the repo again and use the corrected code. 

Alternatively, you can replace the function predict_classes() by the function predict(). For example: 
`mymodel.predict_classes(img)[0][0]`  changes to `mymodel.predict(img)[0][0]`
